version: "3.7"

services:

  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx/
    ports:
      - 2000:80

  mysql:
    container_name: mysql
    image: mysql:8.0.23
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    env_file:
      - ./server/.env
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql:mysql
    ports:
      - 2002:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions